#! /usr/bin/env bash

name=$1
year=$(basename $(pwd))

if [ "$name" == "" ]; then
    echo "Usage: $0 ModuleName"
    exit 1
fi

day=$(date '+%e' | tr -d ' ')
read -p "($year) Date (default: $day): " other_day

if [ "$other_day" != "" ]; then
    day=$other_day
fi

dirname="$day-$name"
mix new $dirname --app aoc --module $name
rm -f $dirname/README.md
rm -f $dirname/.formatter.exs
ln -s ../.formatter.exs $dirname/.formatter.exs

cookie=$(cat .aoc_cookies)
echo -n "Fetching input file..."
curl -s -H "cookie: $cookie" https://adventofcode.com/$year/day/$day/input -o $dirname/input.txt
echo " done."

echo -n "Fetching sample data..."
curl -s -H "cookie: $cookie" https://adventofcode.com/$year/day/$day -o $dirname/day.html
echo " done."
ruby -e 'html = $stdin.read; html.scan(/<pre>[^<]*<code>([^<]*)/) {|c| puts %Q!def sample() do\n"""\n%s"""\nend! % c }' < $dirname/day.html > $dirname/samples.exs
ruby -e 'html = $stdin.read; html.scan(/<pre>[^<]*<code>([^<]*)/) {|c,no| puts %Q!def sample() do\n  [%s]\nend! % c.split.join(",") }' < $dirname/day.html >> $dirname/samples.exs
echo "You might want to copy the samples from $dirname/samples.exs to your code."
cat test_helpers.exs >> $dirname/test/*_test.exs

cmd="code $dirname"
echo -n $cmd | pbcopy
echo "Next: run \`$cmd\`.  It's on the clipboard."
